name: Terraform

on:
  pull_request:
    paths: ['infra/terraform/**', 'infra/terraform-gcp/**']
  push:
    branches: [main]
    paths: ['infra/terraform/**', 'infra/terraform-gcp/**']

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  fmt-validate-tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }

      - name: Terraform fmt (AWS)
        run: terraform fmt -check -recursive infra/terraform
        continue-on-error: true

      - name: Terraform fmt (GCP)
        run: terraform fmt -check -recursive infra/terraform-gcp
        continue-on-error: true

      - name: Validate AWS modules (no backend)
        working-directory: infra/terraform/envs/staging
        run: |
          terraform init -backend=false
          terraform validate
        continue-on-error: true

      - name: Validate GCP modules (no backend)
        working-directory: infra/terraform-gcp/envs/staging
        run: |
          terraform init -backend=false
          terraform validate
        continue-on-error: true

      - name: tfsec scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with: { working_directory: infra }
        continue-on-error: true

  plan-aws-staging:
    runs-on: ubuntu-latest
    needs: fmt-validate-tfsec
    if: github.event_name == 'pull_request'
    steps:
      - id: check
        run: |
          if [ -z "${{ secrets.AWS_DEPLOY_ROLE_ARN_STAGING }}" ]; then
            echo "::notice::AWS plan skipped (no AWS_DEPLOY_ROLE_ARN_STAGING)"
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: steps.check.outputs.skip != 'true'
      - uses: hashicorp/setup-terraform@v3
        if: steps.check.outputs.skip != 'true'
        with: { terraform_version: 1.7.5 }
      - uses: aws-actions/configure-aws-credentials@v4
        if: steps.check.outputs.skip != 'true'
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN_STAGING }}
          aws-region: eu-west-3
      - name: Plan
        if: steps.check.outputs.skip != 'true'
        working-directory: infra/terraform/envs/staging
        run: |
          terraform init
          terraform plan -no-color -lock-timeout=5m
